// Shared content + copy for the Heard It First prototypes (mobile + web).
// Both templates read window.HIF, so content stays in sync across the two.
// Every ticker in UNIVERSE has a full FOLLOWS record and at least one NEWS item,
// so following a new ticker produces real data everywhere it appears.
(function(){
const NEWS = [
  { ticker:'NVDA', source:'Reuters', stamp:'09:29:14', score:'+72', delta:'+2.4%', up:true, vol:'1.8x',
    headline:{ EN:'Data-centre guidance raised for the third straight quarter', RO:'Estimările pentru centrele de date, majorate al treilea trimestru consecutiv', DE:'Data-Center-Prognose zum dritten Quartal in Folge erhöht' },
    watch:{ EN:'Order book concentration — top three customers are 41% of revenue.', RO:'Concentrarea comenzilor — primii trei clienți acoperă 41% din venituri.', DE:'Konzentration im Auftragsbuch — die drei größten Kunden stehen für 41% des Umsatzes.' } },
  { ticker:'AAPL', source:'Bloomberg', stamp:'08:53:02', score:'+18', delta:'+0.3%', up:true, vol:'0.9x',
    headline:{ EN:'Services revenue in India up 34% year on year', RO:'Veniturile din servicii în India, plus 34% de la an la an', DE:'Services-Umsatz in Indien 34% über Vorjahr' },
    watch:{ EN:'Services margin, not headline growth — it carries the multiple.', RO:'Marja din servicii, nu creșterea din titlu — ea susține multiplul.', DE:'Die Services-Marge, nicht das Umsatzwachstum — sie trägt das Multiple.' } },
  { ticker:'TSLA', source:'WSJ', stamp:'08:11:47', score:'−34', delta:'−1.8%', up:false, vol:'2.3x',
    headline:{ EN:'Second European price cut this quarter', RO:'A doua reducere de preț în Europa în acest trimestru', DE:'Zweite Preissenkung in Europa in diesem Quartal' },
    watch:{ EN:'Gross margin ex-credits at the next print.', RO:'Marja brută fără credite de mediu, la următorul raport.', DE:'Bruttomarge ohne Emissionsgutschriften im nächsten Bericht.' } },
  { ticker:'MSFT', source:'CNBC', stamp:'09:12:38', score:'+26', delta:'+0.6%', up:true, vol:'1.1x',
    headline:{ EN:'Azure AI capacity sold out through the first half', RO:'Capacitatea Azure AI, vândută integral până la jumătatea anului', DE:'Azure-AI-Kapazität bis zur Jahresmitte ausverkauft' },
    watch:{ EN:'Capex guide, not the sell-out — the spend lands before the revenue.', RO:'Ghidajul de investiții, nu vânzarea integrală — cheltuiala vine înaintea veniturilor.', DE:'Der Capex-Ausblick, nicht der Ausverkauf — die Ausgaben kommen vor dem Umsatz.' } },
  { ticker:'AMZN', source:'The Information', stamp:'08:34:19', score:'−12', delta:'−0.9%', up:false, vol:'1.4x',
    headline:{ EN:'Retail margin slips as one-day delivery expands', RO:'Marja din retail scade pe măsură ce livrarea într-o zi se extinde', DE:'Retail-Marge sinkt mit dem Ausbau der Ein-Tag-Lieferung' },
    watch:{ EN:'AWS operating income covers it — watch the segment split.', RO:'Profitul operațional AWS acoperă diferența — urmărește defalcarea pe segmente.', DE:'Das AWS-Betriebsergebnis fängt es auf — auf die Segmentaufteilung achten.' } },
  { ticker:'ASML', source:'FT', stamp:'07:52:05', score:'+44', delta:'+1.7%', up:true, vol:'1.6x',
    headline:{ EN:'High-NA bookings from two more logic customers', RO:'Comenzi High-NA de la încă doi clienți din segmentul logic', DE:'High-NA-Bestellungen von zwei weiteren Logik-Kunden' },
    watch:{ EN:'Backlog converts slowly — recognition is 2027 revenue.', RO:'Portofoliul se convertește lent — recunoașterea e venit de 2027.', DE:'Der Auftragsbestand wandelt sich langsam — Umsatz erst 2027.' } },
  { ticker:'NOVO', source:'Reuters', stamp:'07:21:44', score:'−28', delta:'−2.6%', up:false, vol:'2.0x',
    headline:{ EN:'US payer drops obesity drug from two formularies', RO:'Un asigurător american scoate medicamentul pentru obezitate din două liste', DE:'US-Kostenträger nimmt Abnehmmittel aus zwei Listen' },
    watch:{ EN:'Net price, not volume — rebates are where the story is.', RO:'Prețul net, nu volumul — povestea e la reduceri.', DE:'Der Nettopreis, nicht das Volumen — die Story steckt in den Rabatten.' } },
  { ticker:'NVDA', source:'The Verge', stamp:'07:40:22', score:'+9', delta:'+2.4%', up:true, vol:'1.8x',
    headline:{ EN:'Rival inference chip ships at roughly half the price', RO:'Un chip de inferență concurent se lansează la aproximativ jumătate de preț', DE:'Konkurrierender Inferenz-Chip kommt zum halben Preis' },
    watch:{ EN:'Low-end share loss first; no near-term revenue impact.', RO:'Mai întâi pierdere de cotă la gama inferioară; fără impact imediat pe venituri.', DE:'Zunächst Marktanteilsverlust im Einstiegssegment; kurzfristig kein Umsatzeffekt.' } },
  { ticker:'AAPL', source:'FT', stamp:'06:58:31', score:'−6', delta:'+0.3%', up:true, vol:'0.9x',
    headline:{ EN:'EU regulator requests further App Store fee disclosure', RO:'Autoritatea UE cere date suplimentare despre comisioanele App Store', DE:'EU-Behörde fordert weitere Angaben zu App-Store-Gebühren' },
    watch:{ EN:'Inquiry, not a ruling — historically moves only on a fine.', RO:'O anchetă, nu o decizie — istoric, mișcă prețul doar la amendă.', DE:'Eine Prüfung, kein Urteil — bewegt den Kurs historisch erst bei einer Strafe.' } },
  { ticker:'MSFT', source:'Bloomberg', stamp:'06:44:10', score:'+7', delta:'+0.6%', up:true, vol:'1.1x',
    headline:{ EN:'Copilot seat additions slow at enterprise renewals', RO:'Adăugarea de licențe Copilot încetinește la reînnoirile enterprise', DE:'Copilot-Lizenzzuwachs bei Enterprise-Verlängerungen verlangsamt' },
    watch:{ EN:'Seat count is the tell for the AI revenue line.', RO:'Numărul de licențe e indiciul pentru linia de venituri AI.', DE:'Die Lizenzzahl ist der Indikator für die AI-Umsatzlinie.' } },
  { ticker:'TSLA', source:'Handelsblatt', stamp:'06:30:52', score:'−9', delta:'−1.8%', up:false, vol:'2.3x',
    headline:{ EN:'Berlin plant runs a shortened shift pattern in September', RO:'Uzina din Berlin trece pe program redus în septembrie', DE:'Werk Berlin fährt im September verkürzte Schichten' },
    watch:{ EN:'Output cut ahead of the quarter-end delivery number.', RO:'Producție redusă înainte de cifra de livrări de la final de trimestru.', DE:'Produktionskürzung vor der Auslieferungszahl zum Quartalsende.' } }
];
const FOLLOWS = {
  NVDA: { ticker:'NVDA', name:'NVIDIA Corp', price:'184.20', move:'+2.4%', up:true, score:'+72', buyPct:'79%', analystDetail:'41 / 9 / 2', earnDays:'12d', earnDate:'14 Sep', perf6m:'+41.8%',
    latest:{ EN:'3 stories · 1h', RO:'3 știri · 1h', DE:'3 Meldungen · 1h' },
    call:{ EN:'Raised guidance is priced in; the risk is customer concentration, not demand.', RO:'Estimările majorate sunt deja în preț; riscul e concentrarea clienților, nu cererea.', DE:'Die höhere Prognose ist eingepreist; das Risiko ist die Kundenkonzentration, nicht die Nachfrage.' } },
  AAPL: { ticker:'AAPL', name:'Apple Inc', price:'241.06', move:'+0.3%', up:true, score:'+18', buyPct:'42%', analystDetail:'19 / 22 / 4', earnDays:'34d', earnDate:'06 Oct', perf6m:'+11.2%',
    latest:{ EN:'2 stories · 3h', RO:'2 știri · 3h', DE:'2 Meldungen · 3h' },
    call:{ EN:'Services growth is the story; the EU inquiry is noise until a number is attached.', RO:'Creșterea serviciilor e subiectul; ancheta UE e zgomot până apare o cifră.', DE:'Das Services-Wachstum ist die Story; die EU-Prüfung ist Rauschen, solange keine Zahl daran hängt.' } },
  TSLA: { ticker:'TSLA', name:'Tesla Inc', price:'318.77', move:'−1.8%', up:false, score:'−34', buyPct:'28%', analystDetail:'12 / 20 / 11', earnDays:'21d', earnDate:'23 Sep', perf6m:'−7.4%',
    latest:{ EN:'4 stories · 2h', RO:'4 știri · 2h', DE:'4 Meldungen · 2h' },
    call:{ EN:'Volume is being bought with margin. Watch gross margin ex-credits.', RO:'Volumul e cumpărat cu marjă. Urmărește marja brută fără credite.', DE:'Volumen wird mit Marge gekauft. Bruttomarge ohne Gutschriften beobachten.' } },
  MSFT: { ticker:'MSFT', name:'Microsoft Corp', price:'512.40', move:'+0.6%', up:true, score:'+26', buyPct:'86%', analystDetail:'48 / 6 / 1', earnDays:'26d', earnDate:'28 Sep', perf6m:'+18.9%',
    latest:{ EN:'2 stories · 2h', RO:'2 știri · 2h', DE:'2 Meldungen · 2h' },
    call:{ EN:'Sold-out capacity is a demand signal; the capex guide is the cost of it.', RO:'Capacitatea epuizată e un semnal de cerere; ghidajul de investiții e costul ei.', DE:'Ausverkaufte Kapazität ist ein Nachfragesignal; der Capex-Ausblick ist der Preis dafür.' } },
  AMZN: { ticker:'AMZN', name:'Amazon.com Inc', price:'238.15', move:'−0.9%', up:false, score:'−12', buyPct:'71%', analystDetail:'39 / 12 / 3', earnDays:'18d', earnDate:'20 Sep', perf6m:'+6.1%',
    latest:{ EN:'1 story · 4h', RO:'1 știre · 4h', DE:'1 Meldung · 4h' },
    call:{ EN:'Retail margin is the swing factor; AWS is doing the earning.', RO:'Marja din retail e factorul volatil; AWS aduce profitul.', DE:'Die Retail-Marge ist der Schwankungsfaktor; AWS verdient das Geld.' } },
  ASML: { ticker:'ASML', name:'ASML Holding NV', price:'892.10', move:'+1.7%', up:true, score:'+44', buyPct:'74%', analystDetail:'26 / 8 / 1', earnDays:'41d', earnDate:'13 Oct', perf6m:'+24.5%',
    latest:{ EN:'1 story · 5h', RO:'1 știre · 5h', DE:'1 Meldung · 5h' },
    call:{ EN:'Bookings are 2027 revenue — good news, slow money.', RO:'Comenzile sunt venit de 2027 — știre bună, bani lenți.', DE:'Bestellungen sind Umsatz für 2027 — gute Nachricht, langsames Geld.' } },
  NOVO: { ticker:'NOVO', name:'Novo Nordisk A/S', price:'61.83', move:'−2.6%', up:false, score:'−28', buyPct:'55%', analystDetail:'17 / 13 / 4', earnDays:'9d', earnDate:'11 Sep', perf6m:'−19.3%',
    latest:{ EN:'1 story · 6h', RO:'1 știre · 6h', DE:'1 Meldung · 6h' },
    call:{ EN:'Formulary losses hit net price before they hit volume.', RO:'Pierderea listelor de rambursare lovește prețul net înainte de volum.', DE:'Listenverluste treffen den Nettopreis vor dem Volumen.' } }
};
const UNIVERSE = [
  { ticker:'NVDA', name:'NVIDIA Corp', stories:'28' },
  { ticker:'AAPL', name:'Apple Inc', stories:'19' },
  { ticker:'TSLA', name:'Tesla Inc', stories:'31' },
  { ticker:'MSFT', name:'Microsoft Corp', stories:'14' },
  { ticker:'AMZN', name:'Amazon.com Inc', stories:'22' },
  { ticker:'ASML', name:'ASML Holding NV', stories:'6' },
  { ticker:'NOVO', name:'Novo Nordisk A/S', stories:'11' }
];
const UI = {
  EN: { terminal:'Terminal build · v2', mobile:'Mobile', desktop:'Desktop', free:'Free', pro:'Pro', viewPro:'View as Pro', viewFree:'View as Free',
    interval:'Scan interval', sources:'Sources', pitch:'Every followed ticker scanned on the interval you set. Push the moment a story lands, not on the next refresh.',
    contGoogle:'Continue with Google', contApple:'Continue with Apple', contEmail:'Continue with email',
    feed:'Feed', following:'Following', market:'Market', score:'Score', volAvg:'Vol vs avg', source:'Source', watch:'Watch',
    delayed24:'Delayed 24 h', proYesterday:'Pro read this yesterday', removeDelay:'Remove the delay', delayLabel:'delay 24h', lastScan:'last scan 09:41',
    watchlist:'Watchlist', ticker:'Ticker', last:'Last', chg:'Chg', pushOff:'push off', pushOn:'push 30m', addTicker:'Add ticker',
    capNote:'Free caps the list at three and never pushes. Pro is uncapped at a 30-minute interval.', liftCap:'Lift the cap',
    stories24:'stories 24h', storiesWord:'stories', add:'Add', added:'Added', remove:'Remove', match:'Match', topVolume:'Highest news volume · 24h',
    backFeed:'← Feed', back:'← Back', newsScore:'News score', storiesN:'28 stories', analyst:'Analyst', earnings:'Earnings', theCall:'The call', tape:'Tape',
    freqFree:'Free: 24h delay, no push, one scan a day.', freqPro:'Push fires the moment a scan returns a match.',
    addToList:'Add %s to watchlist', enablePush:'Enable push · upgrade', pushEnabled:'Push enabled · %s',
    paywallTitle:'A full day of edge', paywallSub:'Free reads the news 24 hours late. Pro reads it as it lands.',
    perMonth:'/ mo · $60 / yr', start7:'Start 7 days free', stayFree:'Stay on Free',
    rowLatency:'Feed latency', rowTickers:'Tickers followed', rowPush:'Push notifications', rowAnalyst:'Analyst breakdown', rowChart:'Chart history', rowDigest:'Pre-open digest', unlimited:'Unlimited', full:'Full', max:'Max',
    more:'More', portfolio:'Portfolio', portfolioNote:'Cost basis, weight, P/L against the news', calendar:'Earnings calendar', calendarNote:'Dates and surprise history per ticker',
    screener:'Screener', screenerNote:'Filter by news volume and score', digests:'Digests', digestsNote:'06:30 pre-open email', broker:'Broker link', brokerNote:'Import holdings automatically',
    account:'Account', plan:'Plan', tickers:'Tickers', appLang:'App language', contentLang:'Content language',
    appLangNote:'Buttons, labels and menus appear in English.', quiet:'Quiet hours · 22:00–07:00', manageSub:'Manage subscription', signOut:'Sign out',
    upgradeBtn:'Upgrade · $7/mo', managePro:'Manage Pro', goPro:'Go Pro', removed:'Removed', noNews:'No stories in the last 24h',
    notifTickers:'Followed tickers', notifTickersNote:'Push on scan match', notifMove:'Move threshold', notifMoveNote:'Absolute daily change', notifQuiet:'Quiet hours', notifQuietNote:'Suppressed overnight',
    tabFeed:'Feed', tabList:'List', tabAdd:'Add', tabMore:'More', tabYou:'You', langNote:'News, watch notes and alerts are delivered in English.' },
  RO: { terminal:'Versiune terminal · v2', mobile:'Mobil', desktop:'Desktop', free:'Gratuit', pro:'Pro', viewPro:'Vezi ca Pro', viewFree:'Vezi ca Gratuit',
    interval:'Interval scanare', sources:'Surse', pitch:'Fiecare simbol urmărit este scanat la intervalul stabilit. Notificarea pleacă în momentul apariției știrii, nu la următoarea reîmprospătare.',
    contGoogle:'Continuă cu Google', contApple:'Continuă cu Apple', contEmail:'Continuă cu e-mail',
    feed:'Flux', following:'Urmărite', market:'Piață', score:'Scor', volAvg:'Vol vs medie', source:'Sursă', watch:'Urmărește',
    delayed24:'Întârziat 24 h', proYesterday:'Pro a citit asta ieri', removeDelay:'Elimină întârzierea', delayLabel:'întârziere 24h', lastScan:'ultima scanare 09:41',
    watchlist:'Listă', ticker:'Simbol', last:'Ultim', chg:'Var', pushOff:'fără push', pushOn:'push 30m', addTicker:'Adaugă simbol',
    capNote:'Varianta gratuită limitează lista la trei și nu trimite notificări. Pro nu are limită, cu scanare la 30 de minute.', liftCap:'Ridică limita',
    stories24:'știri 24h', storiesWord:'știri', add:'Adaugă', added:'Adăugat', remove:'Elimină', match:'Rezultat', topVolume:'Cel mai mare volum de știri · 24h',
    backFeed:'← Flux', back:'← Înapoi', newsScore:'Scor știri', storiesN:'28 știri', analyst:'Analiști', earnings:'Raportare', theCall:'Concluzia', tape:'Fluxul',
    freqFree:'Gratuit: întârziere 24h, fără notificări, o scanare pe zi.', freqPro:'Notificarea pleacă imediat ce scanarea găsește ceva.',
    addToList:'Adaugă %s în listă', enablePush:'Activează notificările · upgrade', pushEnabled:'Notificări active · %s',
    paywallTitle:'O zi întreagă de avans', paywallSub:'Gratuit citește știrile cu 24 de ore întârziere. Pro le citește când apar.',
    perMonth:'/ lună · 60 $ / an', start7:'Începe 7 zile gratuit', stayFree:'Rămân pe Gratuit',
    rowLatency:'Întârziere flux', rowTickers:'Simboluri urmărite', rowPush:'Notificări push', rowAnalyst:'Detalii analiști', rowChart:'Istoric grafic', rowDigest:'Sumar pre-deschidere', unlimited:'Nelimitat', full:'Complet', max:'Maxim',
    more:'Mai multe', portfolio:'Portofoliu', portfolioNote:'Cost de achiziție, pondere, profit/pierdere față de știri', calendar:'Calendar raportări', calendarNote:'Date și istoric al surprizelor pe simbol',
    screener:'Filtrare', screenerNote:'Filtrează după volumul de știri și scor', digests:'Sumare', digestsNote:'E-mail la 06:30, înainte de deschidere', broker:'Conectare broker', brokerNote:'Importă automat pozițiile',
    account:'Cont', plan:'Plan', tickers:'Simboluri', appLang:'Limba aplicației', contentLang:'Limba conținutului',
    appLangNote:'Butoanele, etichetele și meniurile apar în română.', quiet:'Ore silențioase · 22:00–07:00', manageSub:'Gestionează abonamentul', signOut:'Deconectare',
    upgradeBtn:'Upgrade · 7 $/lună', managePro:'Gestionează Pro', goPro:'Trec pe Pro', removed:'Eliminat', noNews:'Nicio știre în ultimele 24h',
    notifTickers:'Simboluri urmărite', notifTickersNote:'Notificare la potrivire', notifMove:'Prag de variație', notifMoveNote:'Variație zilnică absolută', notifQuiet:'Ore silențioase', notifQuietNote:'Blocate peste noapte',
    tabFeed:'Flux', tabList:'Listă', tabAdd:'Adaugă', tabMore:'Mai mult', tabYou:'Tu', langNote:'Știrile, notele și alertele sunt livrate în română.' },
  DE: { terminal:'Terminal-Build · v2', mobile:'Mobil', desktop:'Desktop', free:'Gratis', pro:'Pro', viewPro:'Als Pro ansehen', viewFree:'Als Gratis ansehen',
    interval:'Scan-Intervall', sources:'Quellen', pitch:'Jeder verfolgte Ticker wird im festgelegten Intervall gescannt. Push kommt, sobald eine Meldung erscheint — nicht erst beim nächsten Aktualisieren.',
    contGoogle:'Weiter mit Google', contApple:'Weiter mit Apple', contEmail:'Weiter mit E-Mail',
    feed:'Feed', following:'Verfolgt', market:'Markt', score:'Score', volAvg:'Vol vs Ø', source:'Quelle', watch:'Beachten',
    delayed24:'24 Std. verzögert', proYesterday:'Pro hat das gestern gelesen', removeDelay:'Verzögerung entfernen', delayLabel:'Verzögerung 24 Std.', lastScan:'letzter Scan 09:41',
    watchlist:'Watchlist', ticker:'Ticker', last:'Letzter', chg:'Änd', pushOff:'kein Push', pushOn:'Push 30m', addTicker:'Ticker hinzufügen',
    capNote:'Gratis begrenzt die Liste auf drei und sendet keine Pushes. Pro ist unbegrenzt, im 30-Minuten-Intervall.', liftCap:'Limit aufheben',
    stories24:'Meldungen 24 Std.', storiesWord:'Meldungen', add:'Hinzu', added:'Hinzugefügt', remove:'Entfernen', match:'Treffer', topVolume:'Höchstes Meldungsvolumen · 24 Std.',
    backFeed:'← Feed', back:'← Zurück', newsScore:'News-Score', storiesN:'28 Meldungen', analyst:'Analysten', earnings:'Zahlen', theCall:'Die Einschätzung', tape:'Tape',
    freqFree:'Gratis: 24 Std. Verzögerung, kein Push, ein Scan pro Tag.', freqPro:'Push wird gesendet, sobald ein Scan etwas findet.',
    addToList:'%s zur Watchlist', enablePush:'Push aktivieren · Upgrade', pushEnabled:'Push aktiv · %s',
    paywallTitle:'Ein ganzer Tag Vorsprung', paywallSub:'Gratis liest die Nachrichten 24 Stunden später. Pro liest sie sofort.',
    perMonth:'/ Mon. · 60 $ / Jahr', start7:'7 Tage gratis starten', stayFree:'Bei Gratis bleiben',
    rowLatency:'Feed-Verzögerung', rowTickers:'Verfolgte Ticker', rowPush:'Push-Benachrichtigungen', rowAnalyst:'Analysten-Details', rowChart:'Chart-Historie', rowDigest:'Digest vor Handelsstart', unlimited:'Unbegrenzt', full:'Voll', max:'Max',
    more:'Mehr', portfolio:'Portfolio', portfolioNote:'Einstandskurs, Gewichtung, G/V im Verhältnis zu den News', calendar:'Zahlenkalender', calendarNote:'Termine und Überraschungshistorie pro Ticker',
    screener:'Screener', screenerNote:'Nach Meldungsvolumen und Score filtern', digests:'Digests', digestsNote:'E-Mail um 06:30 vor Handelsstart', broker:'Broker-Anbindung', brokerNote:'Positionen automatisch importieren',
    account:'Konto', plan:'Tarif', tickers:'Ticker', appLang:'App-Sprache', contentLang:'Inhaltssprache',
    appLangNote:'Buttons, Bezeichnungen und Menüs erscheinen auf Deutsch.', quiet:'Ruhezeiten · 22:00–07:00', manageSub:'Abo verwalten', signOut:'Abmelden',
    upgradeBtn:'Upgrade · 7 $/Mon.', managePro:'Pro verwalten', goPro:'Pro holen', removed:'Entfernt', noNews:'Keine Meldungen in den letzten 24 Std.',
    notifTickers:'Verfolgte Ticker', notifTickersNote:'Push bei Scan-Treffer', notifMove:'Bewegungsschwelle', notifMoveNote:'Absolute Tagesveränderung', notifQuiet:'Ruhezeiten', notifQuietNote:'Nachts unterdrückt',
    tabFeed:'Feed', tabList:'Liste', tabAdd:'Neu', tabMore:'Mehr', tabYou:'Du', langNote:'Meldungen, Hinweise und Alerts werden auf Deutsch geliefert.' }
};
window.HIF = { NEWS, FOLLOWS, UNIVERSE, UI };
})();
