// Shared content + copy for the Heard It First prototypes (mobile + web).
// Both templates read window.HIF, so content stays in sync across the two.
// Every ticker in FOLLOWS has a full record and at least one NEWS item. UNIVERSE is wider than
// FOLLOWS on purpose — it is the searchable market. Tickers present in UNIVERSE but not in FOLLOWS
// carry no demo data and are surfaced as "live data required" until a Finnhub token is connected.
(function(){
const NEWS = [
  { ticker:'NVDA', source:'Reuters', stamp:'09:29:14', score:'+72', delta:'+2.4%', up:true, vol:'1.8x',
    headline:{ EN:'Data-centre guidance raised for the third straight quarter', RO:'Estimările pentru centrele de date, majorate al treilea trimestru consecutiv', DE:'Data-Center-Prognose zum dritten Quartal in Folge erhöht' },
    watch:{ EN:'Order book concentration — top three customers are 41% of revenue.', RO:'Concentrarea comenzilor — primii trei clienți acoperă 41% din venituri.', DE:'Konzentration im Auftragsbuch — die drei größten Kunden stehen für 41% des Umsatzes.' } },
  { ticker:'AAPL', source:'Bloomberg', stamp:'08:53:02', score:'+18', delta:'+0.3%', up:true, vol:'0.9x',
    headline:{ EN:'Services revenue in India up 34% year on year', RO:'Veniturile din servicii în India, plus 34% de la an la an', DE:'Services-Umsatz in Indien 34% über Vorjahr' },
    watch:{ EN:'Services margin, not headline growth — it carries the multiple.', RO:'Marja din servicii, nu creșterea din titlu — ea susține multiplul.', DE:'Die Services-Marge, nicht das Umsatzwachstum — sie trägt das Multiple.' } },
  { ticker:'TSLA', source:'WSJ', stamp:'08:11:47', score:'−34', delta:'−1.8%', up:false, vol:'2.3x',
    headline:{ EN:'Second European price cut this quarter', RO:'A doua reducere de preț în Europa în acest trimestru', DE:'Zweite Preissenkung in Europa in diesem Quartal' },
    watch:{ EN:'Gross margin ex-credits at the next print.', RO:'Marja brută fără credite de mediu, la următorul raport.', DE:'Bruttomarge ohne Emissionsgutschriften im nächsten Bericht.' } },
  { ticker:'MSFT', source:'CNBC', stamp:'09:12:38', score:'+26', delta:'+0.6%', up:true, vol:'1.1x',
    headline:{ EN:'Azure AI capacity sold out through the first half', RO:'Capacitatea Azure AI, vândută integral până la jumătatea anului', DE:'Azure-AI-Kapazität bis zur Jahresmitte ausverkauft' },
    watch:{ EN:'Capex guide, not the sell-out — the spend lands before the revenue.', RO:'Ghidajul de investiții, nu vânzarea integrală — cheltuiala vine înaintea veniturilor.', DE:'Der Capex-Ausblick, nicht der Ausverkauf — die Ausgaben kommen vor dem Umsatz.' } },
  { ticker:'AMZN', source:'The Information', stamp:'08:34:19', score:'−12', delta:'−0.9%', up:false, vol:'1.4x',
    headline:{ EN:'Retail margin slips as one-day delivery expands', RO:'Marja din retail scade pe măsură ce livrarea într-o zi se extinde', DE:'Retail-Marge sinkt mit dem Ausbau der Ein-Tag-Lieferung' },
    watch:{ EN:'AWS operating income covers it — watch the segment split.', RO:'Profitul operațional AWS acoperă diferența — urmărește defalcarea pe segmente.', DE:'Das AWS-Betriebsergebnis fängt es auf — auf die Segmentaufteilung achten.' } },
  { ticker:'ASML', source:'FT', stamp:'07:52:05', score:'+44', delta:'+1.7%', up:true, vol:'1.6x',
    headline:{ EN:'High-NA bookings from two more logic customers', RO:'Comenzi High-NA de la încă doi clienți din segmentul logic', DE:'High-NA-Bestellungen von zwei weiteren Logik-Kunden' },
    watch:{ EN:'Backlog converts slowly — recognition is 2027 revenue.', RO:'Portofoliul se convertește lent — recunoașterea e venit de 2027.', DE:'Der Auftragsbestand wandelt sich langsam — Umsatz erst 2027.' } },
  { ticker:'NOVO', source:'Reuters', stamp:'07:21:44', score:'−28', delta:'−2.6%', up:false, vol:'2.0x',
    headline:{ EN:'US payer drops obesity drug from two formularies', RO:'Un asigurător american scoate medicamentul pentru obezitate din două liste', DE:'US-Kostenträger nimmt Abnehmmittel aus zwei Listen' },
    watch:{ EN:'Net price, not volume — rebates are where the story is.', RO:'Prețul net, nu volumul — povestea e la reduceri.', DE:'Der Nettopreis, nicht das Volumen — die Story steckt in den Rabatten.' } },
  { ticker:'NVDA', source:'The Verge', stamp:'07:40:22', score:'+9', delta:'+2.4%', up:true, vol:'1.8x',
    headline:{ EN:'Rival inference chip ships at roughly half the price', RO:'Un chip de inferență concurent se lansează la aproximativ jumătate de preț', DE:'Konkurrierender Inferenz-Chip kommt zum halben Preis' },
    watch:{ EN:'Low-end share loss first; no near-term revenue impact.', RO:'Mai întâi pierdere de cotă la gama inferioară; fără impact imediat pe venituri.', DE:'Zunächst Marktanteilsverlust im Einstiegssegment; kurzfristig kein Umsatzeffekt.' } },
  { ticker:'AAPL', source:'FT', stamp:'06:58:31', score:'−6', delta:'+0.3%', up:true, vol:'0.9x',
    headline:{ EN:'EU regulator requests further App Store fee disclosure', RO:'Autoritatea UE cere date suplimentare despre comisioanele App Store', DE:'EU-Behörde fordert weitere Angaben zu App-Store-Gebühren' },
    watch:{ EN:'Inquiry, not a ruling — historically moves only on a fine.', RO:'O anchetă, nu o decizie — istoric, mișcă prețul doar la amendă.', DE:'Eine Prüfung, kein Urteil — bewegt den Kurs historisch erst bei einer Strafe.' } },
  { ticker:'MSFT', source:'Bloomberg', stamp:'06:44:10', score:'+7', delta:'+0.6%', up:true, vol:'1.1x',
    headline:{ EN:'Copilot seat additions slow at enterprise renewals', RO:'Adăugarea de licențe Copilot încetinește la reînnoirile enterprise', DE:'Copilot-Lizenzzuwachs bei Enterprise-Verlängerungen verlangsamt' },
    watch:{ EN:'Seat count is the tell for the AI revenue line.', RO:'Numărul de licențe e indiciul pentru linia de venituri AI.', DE:'Die Lizenzzahl ist der Indikator für die AI-Umsatzlinie.' } },
  { ticker:'TSLA', source:'Handelsblatt', stamp:'06:30:52', score:'−9', delta:'−1.8%', up:false, vol:'2.3x',
    headline:{ EN:'Berlin plant runs a shortened shift pattern in September', RO:'Uzina din Berlin trece pe program redus în septembrie', DE:'Werk Berlin fährt im September verkürzte Schichten' },
    watch:{ EN:'Output cut ahead of the quarter-end delivery number.', RO:'Producție redusă înainte de cifra de livrări de la final de trimestru.', DE:'Produktionskürzung vor der Auslieferungszahl zum Quartalsende.' } }
];
const FOLLOWS = {
  NVDA: { ticker:'NVDA', name:'NVIDIA Corp', price:'184.20', move:'+2.4%', up:true, score:'+72', buyPct:'79%', analystDetail:'41 / 9 / 2', earnDays:'12d', earnDate:'14 Sep', perf6m:'+41.8%', lastEarn:'Beat by 4.2% · 27 Aug',
    latest:{ EN:'3 stories · 1h', RO:'3 știri · 1h', DE:'3 Meldungen · 1h' },
    call:{ EN:'Raised guidance is priced in; the risk is customer concentration, not demand.', RO:'Estimările majorate sunt deja în preț; riscul e concentrarea clienților, nu cererea.', DE:'Die höhere Prognose ist eingepreist; das Risiko ist die Kundenkonzentration, nicht die Nachfrage.' } },
  AAPL: { ticker:'AAPL', name:'Apple Inc', price:'241.06', move:'+0.3%', up:true, score:'+18', buyPct:'42%', analystDetail:'19 / 22 / 4', earnDays:'34d', earnDate:'06 Oct', perf6m:'+11.2%', lastEarn:'Beat by 1.8% · 31 Jul',
    latest:{ EN:'2 stories · 3h', RO:'2 știri · 3h', DE:'2 Meldungen · 3h' },
    call:{ EN:'Services growth is the story; the EU inquiry is noise until a number is attached.', RO:'Creșterea serviciilor e subiectul; ancheta UE e zgomot până apare o cifră.', DE:'Das Services-Wachstum ist die Story; die EU-Prüfung ist Rauschen, solange keine Zahl daran hängt.' } },
  TSLA: { ticker:'TSLA', name:'Tesla Inc', price:'318.77', move:'−1.8%', up:false, score:'−34', buyPct:'28%', analystDetail:'12 / 20 / 11', earnDays:'21d', earnDate:'23 Sep', perf6m:'−7.4%', lastEarn:'Missed by 3.1% · 23 Jul',
    latest:{ EN:'4 stories · 2h', RO:'4 știri · 2h', DE:'4 Meldungen · 2h' },
    call:{ EN:'Volume is being bought with margin. Watch gross margin ex-credits.', RO:'Volumul e cumpărat cu marjă. Urmărește marja brută fără credite.', DE:'Volumen wird mit Marge gekauft. Bruttomarge ohne Gutschriften beobachten.' } },
  MSFT: { ticker:'MSFT', name:'Microsoft Corp', price:'512.40', move:'+0.6%', up:true, score:'+26', buyPct:'86%', analystDetail:'48 / 6 / 1', earnDays:'26d', earnDate:'28 Sep', perf6m:'+18.9%', lastEarn:'Beat by 2.6% · 30 Jul',
    latest:{ EN:'2 stories · 2h', RO:'2 știri · 2h', DE:'2 Meldungen · 2h' },
    call:{ EN:'Sold-out capacity is a demand signal; the capex guide is the cost of it.', RO:'Capacitatea epuizată e un semnal de cerere; ghidajul de investiții e costul ei.', DE:'Ausverkaufte Kapazität ist ein Nachfragesignal; der Capex-Ausblick ist der Preis dafür.' } },
  AMZN: { ticker:'AMZN', name:'Amazon.com Inc', price:'238.15', move:'−0.9%', up:false, score:'−12', buyPct:'71%', analystDetail:'39 / 12 / 3', earnDays:'18d', earnDate:'20 Sep', perf6m:'+6.1%', lastEarn:'Beat by 0.9% · 31 Jul',
    latest:{ EN:'1 story · 4h', RO:'1 știre · 4h', DE:'1 Meldung · 4h' },
    call:{ EN:'Retail margin is the swing factor; AWS is doing the earning.', RO:'Marja din retail e factorul volatil; AWS aduce profitul.', DE:'Die Retail-Marge ist der Schwankungsfaktor; AWS verdient das Geld.' } },
  ASML: { ticker:'ASML', name:'ASML Holding NV', price:'892.10', move:'+1.7%', up:true, score:'+44', buyPct:'74%', analystDetail:'26 / 8 / 1', earnDays:'41d', earnDate:'13 Oct', perf6m:'+24.5%', lastEarn:'Missed by 1.4% · 16 Jul',
    latest:{ EN:'1 story · 5h', RO:'1 știre · 5h', DE:'1 Meldung · 5h' },
    call:{ EN:'Bookings are 2027 revenue — good news, slow money.', RO:'Comenzile sunt venit de 2027 — știre bună, bani lenți.', DE:'Bestellungen sind Umsatz für 2027 — gute Nachricht, langsames Geld.' } },
  NOVO: { ticker:'NOVO', name:'Novo Nordisk A/S', price:'61.83', move:'−2.6%', up:false, score:'−28', buyPct:'55%', analystDetail:'17 / 13 / 4', earnDays:'9d', earnDate:'11 Sep', perf6m:'−19.3%', lastEarn:'Missed by 5.2% · 06 Aug',
    latest:{ EN:'1 story · 6h', RO:'1 știre · 6h', DE:'1 Meldung · 6h' },
    call:{ EN:'Formulary losses hit net price before they hit volume.', RO:'Pierderea listelor de rambursare lovește prețul net înainte de volum.', DE:'Listenverluste treffen den Nettopreis vor dem Volumen.' } }
};
const UNIVERSE = [
  { ticker:'NVDA', name:'NVIDIA Corp', stories:'28' },
  { ticker:'AAPL', name:'Apple Inc', stories:'19' },
  { ticker:'TSLA', name:'Tesla Inc', stories:'31' },
  { ticker:'MSFT', name:'Microsoft Corp', stories:'14' },
  { ticker:'AMZN', name:'Amazon.com Inc', stories:'22' },
  { ticker:'ASML', name:'ASML Holding NV', stories:'6' },
  { ticker:'NOVO', name:'Novo Nordisk A/S', stories:'11' },
  { ticker:'GOOGL', name:'Alphabet Inc', stories:'17' },
  { ticker:'META',  name:'Meta Platforms Inc', stories:'15' },
  { ticker:'AMD',   name:'Advanced Micro Devices', stories:'13' },
  { ticker:'INTC',  name:'Intel Corp', stories:'12' },
  { ticker:'AVGO',  name:'Broadcom Inc', stories:'9' },
  { ticker:'TSM',   name:'Taiwan Semiconductor', stories:'10' },
  { ticker:'MU',    name:'Micron Technology', stories:'8' },
  { ticker:'CRM',   name:'Salesforce Inc', stories:'7' },
  { ticker:'ORCL',  name:'Oracle Corp', stories:'8' },
  { ticker:'NFLX',  name:'Netflix Inc', stories:'11' },
  { ticker:'DIS',   name:'Walt Disney Co', stories:'6' },
  { ticker:'JPM',   name:'JPMorgan Chase & Co', stories:'9' },
  { ticker:'GS',    name:'Goldman Sachs Group', stories:'5' },
  { ticker:'V',     name:'Visa Inc', stories:'6' },
  { ticker:'XOM',   name:'Exxon Mobil Corp', stories:'7' },
  { ticker:'LLY',   name:'Eli Lilly & Co', stories:'12' },
  { ticker:'PFE',   name:'Pfizer Inc', stories:'8' },
  { ticker:'UNH',   name:'UnitedHealth Group', stories:'7' },
  { ticker:'BA',    name:'Boeing Co', stories:'9' },
  { ticker:'CAT',   name:'Caterpillar Inc', stories:'4' },
  { ticker:'KO',    name:'Coca-Cola Co', stories:'3' },
  { ticker:'SAP',   name:'SAP SE', stories:'5' },
  { ticker:'SIE',   name:'Siemens AG', stories:'4' },
  { ticker:'RHM',   name:'Rheinmetall AG', stories:'6' },
  { ticker:'BMW',   name:'Bayerische Motoren Werke AG', stories:'4' },
  { ticker:'SHEL',  name:'Shell plc', stories:'5' },
  { ticker:'BABA',  name:'Alibaba Group Holding', stories:'8' }
];
// Per-ticker calendar. `kind` is a UI key (evEarnings/evExDiv/evPay/evGuide/evDay/evLockup)
// so dates stay language-neutral and the label localizes.
const EVENTS = {
  NVDA: [ { date:'Nov 19', dow:'WED', kind:'evEarnings', detail:'Q3 FY26 · after close' },
          { date:'Nov 26', dow:'WED', kind:'evExDiv',    detail:'$0.01' },
          { date:'Dec 12', dow:'FRI', kind:'evPay',      detail:'$0.01' },
          { date:'Jan 06', dow:'TUE', kind:'evDay',      detail:'CES keynote' } ],
  AAPL: [ { date:'Oct 30', dow:'THU', kind:'evEarnings', detail:'Q4 FY25 · after close' },
          { date:'Nov 07', dow:'FRI', kind:'evExDiv',    detail:'$0.26' },
          { date:'Nov 13', dow:'THU', kind:'evPay',      detail:'$0.26' } ],
  TSLA: [ { date:'Oct 22', dow:'WED', kind:'evEarnings', detail:'Q3 · after close' },
          { date:'Nov 06', dow:'THU', kind:'evGuide',    detail:'Delivery guidance' },
          { date:'Dec 04', dow:'THU', kind:'evDay',      detail:'Shareholder meeting' } ],
  MSFT: [ { date:'Oct 28', dow:'TUE', kind:'evEarnings', detail:'Q1 FY26 · after close' },
          { date:'Nov 20', dow:'THU', kind:'evExDiv',    detail:'$0.83' },
          { date:'Dec 11', dow:'THU', kind:'evPay',      detail:'$0.83' } ],
  AMZN: [ { date:'Oct 30', dow:'THU', kind:'evEarnings', detail:'Q3 · after close' },
          { date:'Dec 02', dow:'TUE', kind:'evGuide',    detail:'Holiday update' } ],
  ASML: [ { date:'Oct 15', dow:'WED', kind:'evEarnings', detail:'Q3 · 07:00 CET' },
          { date:'Oct 23', dow:'THU', kind:'evExDiv',    detail:'€1.60' },
          { date:'Nov 06', dow:'THU', kind:'evPay',      detail:'€1.60' } ],
  NOVO: [ { date:'Nov 05', dow:'WED', kind:'evEarnings', detail:'Q3 · 08:00 CET' },
          { date:'Nov 21', dow:'FRI', kind:'evGuide',    detail:'FY guidance update' } ]
};
// Insider transactions and regulatory filings. Names, forms and figures are
// language-neutral; the row labels come from UI.
const SIGNALS = {
  NVDA: [ { type:'insider', stamp:'3h',  who:'C. Kress',   role:'CFO',      act:'sell', shares:'12,500', value:'$2.30M' },
          { type:'filing',  stamp:'1d',  form:'8-K',       item:'Item 5.02' },
          { type:'insider', stamp:'2d',  who:'J. Huang',   role:'CEO',      act:'sell', shares:'75,000', value:'$13.8M' },
          { type:'filing',  stamp:'6d',  form:'10-Q',      item:'Q2 FY26' } ],
  AAPL: [ { type:'filing',  stamp:'5h',  form:'8-K',       item:'Item 2.02' },
          { type:'insider', stamp:'1d',  who:'T. Cook',    role:'CEO',      act:'sell', shares:'223,986', value:'$50.3M' },
          { type:'insider', stamp:'4d',  who:'K. Adams',   role:'CFO',      act:'sell', shares:'8,400',  value:'$1.88M' } ],
  TSLA: [ { type:'insider', stamp:'8h',  who:'V. Denholm', role:'Chair',    act:'sell', shares:'56,000', value:'$14.1M' },
          { type:'filing',  stamp:'2d',  form:'13D',       item:'5.1% stake' },
          { type:'filing',  stamp:'9d',  form:'S-8',       item:'2026 plan' } ],
  MSFT: [ { type:'insider', stamp:'1d',  who:'A. Hood',    role:'CFO',      act:'sell', shares:'15,000', value:'$6.30M' },
          { type:'filing',  stamp:'3d',  form:'8-K',       item:'Item 5.07' } ],
  AMZN: [ { type:'insider', stamp:'6h',  who:'A. Jassy',   role:'CEO',      act:'sell', shares:'31,200', value:'$6.94M' },
          { type:'filing',  stamp:'5d',  form:'10-Q',      item:'Q3' } ],
  ASML: [ { type:'filing',  stamp:'2d',  form:'6-K',       item:'Q3 release' },
          { type:'insider', stamp:'7d',  who:'R. Dassen',  role:'CFO',      act:'buy',  shares:'2,000',  value:'€1.42M' } ],
  NOVO: [ { type:'filing',  stamp:'1d',  form:'6-K',       item:'Company announcement' },
          { type:'insider', stamp:'4d',  who:'K. Dyekjær', role:'Director', act:'buy',  shares:'1,500',  value:'kr 0.71M' } ]
};
const UI = {
  EN: { terminal:'Terminal build · v2', mobile:'Mobile', desktop:'Desktop', free:'Free', pro:'Pro', viewPro:'View as Pro', viewFree:'View as Free',
    interval:'Scan interval', sources:'Sources', pitch:'Every followed ticker scanned on the interval you set. Push the moment a story lands, not on the next refresh.',
    contGoogle:'Continue with Google', contApple:'Continue with Apple', contEmail:'Continue with email',
    feed:'Feed', following:'Following', market:'Market', score:'Score', volAvg:'Vol vs avg', source:'Source', watch:'Watch',
    delayed24:'Delayed 24 h', proYesterday:'Pro read this yesterday', removeDelay:'Remove the delay', delayLabel:'delay 24h', lastScan:'last scan 09:41',
    watchlist:'Watchlist', ticker:'Ticker', last:'Last', chg:'Chg', pushOff:'push off', pushOn:'push 30m', addTicker:'Add ticker',
    capNote:'Free caps the list at three and never pushes. Pro is uncapped at a 30-minute interval.', liftCap:'Lift the cap',
    stories24:'stories 24h', storiesWord:'stories', add:'Add', added:'Added', remove:'Remove', match:'Match', topVolume:'Highest news volume · 24h',
    backFeed:'← Feed', back:'← Back', newsScore:'News score', storiesN:'28 stories', analyst:'Analyst', earnings:'Earnings', theCall:'The call', tape:'Tape',
    freqFree:'Free: 24h delay, no push, one scan a day.', freqPro:'Push fires the moment a scan returns a match.',
    addToList:'Add %s to watchlist', enablePush:'Enable push · upgrade', pushEnabled:'Push enabled · %s',
    paywallTitle:'A full day of edge', paywallSub:'Free reads the news 24 hours late. Pro reads it as it lands.',
    perMonth:'/ mo · $60 / yr', start7:'Start 7 days free', stayFree:'Stay on Free',
    rowLatency:'Feed latency', rowTickers:'Tickers followed', rowPush:'Push notifications', rowAnalyst:'Analyst breakdown', rowChart:'Chart history', rowDigest:'Pre-open digest', unlimited:'Unlimited', full:'Full', max:'Max',
    more:'More', portfolio:'Portfolio', portfolioNote:'Cost basis, weight, P/L against the news', calendar:'Earnings calendar', calendarNote:'Dates and surprise history per ticker',
    screener:'Screener', screenerNote:'Filter by news volume', noMatch:'No ticker matches', noMatchNote:'Connect a Finnhub token to search the full market beyond the demo universe.', liveReq:'Live', noData:'No data', needsLive:'Live data required', needsLiveNote:'This ticker is outside the demo dataset. Connect a Finnhub token in Tweaks to load its price, chart and stories.', filterAll:'All', filterVol:'Vol ≥ 2×', filterEarn:'Earnings ≤ 14d', filterStories:'Most stories', digests:'Digests', digestsNote:'06:30 pre-open email', broker:'Broker link', brokerNote:'Import holdings automatically',
    account:'Account', plan:'Plan', tickers:'Tickers', appLang:'App language', contentLang:'Content language',
    appLangNote:'Buttons, labels and menus appear in English.', quiet:'Quiet hours · 22:00–07:00', manageSub:'Manage subscription', signOut:'Sign out',
    upgradeBtn:'Upgrade · $7/mo', managePro:'Manage Pro', goPro:'Go Pro', removed:'Removed', noNews:'No stories in the last 24h',
    notifTickers:'Followed tickers', notifTickersNote:'Push on scan match', notifMove:'Move threshold', notifMoveNote:'Absolute daily change', notifQuiet:'Quiet hours', notifQuietNote:'Suppressed overnight',
    alertTypes:'Alert types', alertTypesNote:'What earns a push. Off by default except news.',
    alNews:'Breaking news', alNewsNote:'A story lands on a followed ticker',
    alInsider:'Insider trades', alInsiderNote:'Form 4 buys and sells by officers and directors',
    alFilings:'Regulatory filings', alFilingsNote:'8-K, 10-Q, 13D and other material filings',
    alRating:'Analyst rating changes', alRatingNote:'Upgrades, downgrades and target revisions',
    alEarnings:'Earnings', alEarningsNote:'The moment results are published',
    alMove:'Price move', alMoveNote:'Daily change past your threshold',
    calendarTitle:'Calendar', calendarEmpty:'No scheduled events',
    evEarnings:'Earnings', evExDiv:'Ex-dividend', evPay:'Dividend paid', evGuide:'Guidance', evDay:'Investor event', evLockup:'Lock-up expiry',
    whyTitle:'Why it moved', whyConfidence:'confidence', whyNone:'Nothing explains it',
    conflictTitle:'Where the evidence disagrees', conflictNone:'Analysts, insiders and price all point the same way',
    posTitle:'Your position', posEmpty:'No position', posAdd:'Add position', posEdit:'Edit', posShares:'Shares', posCost:'Cost basis',
    posValue:'Value', posDay:'Today', posTotal:'Since you bought', posSave:'Save', posRemove:'Remove', posWeight:'of portfolio',
    crowdTitle:'Crowding', crowdOf:'of users hold this', crowdContrarian:'Barely held — you are early or alone',
    crowdCrowded:'Heavily crowded — exits get narrow when sentiment turns', crowdNormal:'Normal ownership',
    crowdBook:'Portfolio crowding', crowdBookNote:'Weighted by position size',
    zoneEdge:'Sparse', zoneNormal:'Normal', zoneCrowded:'Crowded', zoneAlarm:'Very crowded',
    ledger:'Ledger', ledgerTitle:'Regret ledger', ledgerNote:'Every story you dismissed, and what the price did next.',
    ledgerEmpty:'Nothing dismissed yet. Skip a story in the feed and it lands here.',
    ledgerMissed:'Missed', ledgerDodged:'Dodged', ledgerFlat:'No move', ledgerPendingRow:'Tracking', ledgerSince:'since you skipped',
    ledgerScore:'Skip accuracy', ledgerScoreNote:'Judged skips only', ledgerClear:'Clear ledger',
    ledgerPending:'Pending', ledgerPendingNote:'Too early to call', ledgerAll:'All', ledgerUndo:'Undo', ledgerEmptyFilter:'Nothing in this bucket yet.',
    dismiss:'Skip', dismissed:'Skipped — tracking it',
    auditTitle:'Security activity', auditNote:'Append-only. Kept on this account, newest first.',
    auditEmpty:'Nothing recorded yet.',
    evSignin:'Signed in', evSignout:'Signed out', evSignoutAll:'Signed out everywhere',
    evTwofaOn:'Two-factor turned on', evTwofaOff:'Two-factor turned off',
    evDeviceRevoked:'Device revoked', evLocked:'Locked on idle', evUnlockFailed:'Failed unlock',
    evPasswordChanged:'Password changed',
    stack:'Stack', stackTitle:'Compare stack', stackShow:'Stack', stackHide:'Hide',
    stackEmpty:'Pin tickers — press P on a feed row, or ⌘K then +NVDA — to read them on one scale.',
    stackPin:'Pin', stackUnpin:'Unpin', stackClear:'Clear stack', stackNorm:'Indexed to 100 · 1 month',
    stackSpread:'Spread', stackCrowdCol:'Crowding', stackAccCol:'Skips', stackLead:'Leader', stackLag:'Laggard',
    cmdPlaceholder:'NVDA · +NVDA to pin · vol>2 · ledger',
    cmdOpenHint:'Open', cmdPinHint:'Pin to stack', cmdScreenHint:'Screen', cmdGoHint:'Go to', cmdNone:'No match',
    cmdKeys:'⌘K command · J / K move · P pin · X skip · Enter open',
    signalsTitle:'Insider & filings', signalsEmpty:'No filings in the last 30 days',
    sigBuy:'bought', sigSell:'sold', sigFiling:'Filing', sigShares:'sh',
    tabFeed:'Feed', tabList:'List', tabAdd:'Add', tabMore:'More', tabYou:'You', langNote:'News, watch notes and alerts are delivered in English.' },
  RO: { terminal:'Versiune terminal · v2', mobile:'Mobil', desktop:'Desktop', free:'Gratuit', pro:'Pro', viewPro:'Vezi ca Pro', viewFree:'Vezi ca Gratuit',
    interval:'Interval scanare', sources:'Surse', pitch:'Fiecare simbol urmărit este scanat la intervalul stabilit. Notificarea pleacă în momentul apariției știrii, nu la următoarea reîmprospătare.',
    contGoogle:'Continuă cu Google', contApple:'Continuă cu Apple', contEmail:'Continuă cu e-mail',
    feed:'Flux', following:'Urmărite', market:'Piață', score:'Scor', volAvg:'Vol vs medie', source:'Sursă', watch:'Urmărește',
    delayed24:'Întârziat 24 h', proYesterday:'Pro a citit asta ieri', removeDelay:'Elimină întârzierea', delayLabel:'întârziere 24h', lastScan:'ultima scanare 09:41',
    watchlist:'Listă', ticker:'Simbol', last:'Ultim', chg:'Var', pushOff:'fără push', pushOn:'push 30m', addTicker:'Adaugă simbol',
    capNote:'Varianta gratuită limitează lista la trei și nu trimite notificări. Pro nu are limită, cu scanare la 30 de minute.', liftCap:'Ridică limita',
    stories24:'știri 24h', storiesWord:'știri', add:'Adaugă', added:'Adăugat', remove:'Elimină', match:'Rezultat', topVolume:'Cel mai mare volum de știri · 24h',
    backFeed:'← Flux', back:'← Înapoi', newsScore:'Scor știri', storiesN:'28 știri', analyst:'Analiști', earnings:'Raportare', theCall:'Concluzia', tape:'Fluxul',
    freqFree:'Gratuit: întârziere 24h, fără notificări, o scanare pe zi.', freqPro:'Notificarea pleacă imediat ce scanarea găsește ceva.',
    addToList:'Adaugă %s în listă', enablePush:'Activează notificările · upgrade', pushEnabled:'Notificări active · %s',
    paywallTitle:'O zi întreagă de avans', paywallSub:'Gratuit citește știrile cu 24 de ore întârziere. Pro le citește când apar.',
    perMonth:'/ lună · 60 $ / an', start7:'Începe 7 zile gratuit', stayFree:'Rămân pe Gratuit',
    rowLatency:'Întârziere flux', rowTickers:'Simboluri urmărite', rowPush:'Notificări push', rowAnalyst:'Detalii analiști', rowChart:'Istoric grafic', rowDigest:'Sumar pre-deschidere', unlimited:'Nelimitat', full:'Complet', max:'Maxim',
    more:'Mai multe', portfolio:'Portofoliu', portfolioNote:'Cost de achiziție, pondere, profit/pierdere față de știri', calendar:'Calendar raportări', calendarNote:'Date și istoric al surprizelor pe simbol',
    screener:'Filtrare', screenerNote:'Filtrează după volumul de știri', noMatch:'Niciun simbol găsit', noMatchNote:'Conectează un token Finnhub pentru a căuta în toată piața, dincolo de universul demo.', liveReq:'Live', noData:'Fără date', needsLive:'Necesită date live', needsLiveNote:'Acest simbol este în afara setului demo. Conectează un token Finnhub în Tweaks pentru preț, grafic și știri.', filterAll:'Toate', filterVol:'Vol ≥ 2×', filterEarn:'Raportare ≤ 14z', filterStories:'Cele mai multe știri', digests:'Sumare', digestsNote:'E-mail la 06:30, înainte de deschidere', broker:'Conectare broker', brokerNote:'Importă automat pozițiile',
    account:'Cont', plan:'Plan', tickers:'Simboluri', appLang:'Limba aplicației', contentLang:'Limba conținutului',
    appLangNote:'Butoanele, etichetele și meniurile apar în română.', quiet:'Ore silențioase · 22:00–07:00', manageSub:'Gestionează abonamentul', signOut:'Deconectare',
    upgradeBtn:'Upgrade · 7 $/lună', managePro:'Gestionează Pro', goPro:'Trec pe Pro', removed:'Eliminat', noNews:'Nicio știre în ultimele 24h',
    alertTypes:'Tipuri de alerte', alertTypesNote:'Ce declanșează o notificare. Doar știrile sunt active implicit.',
    alNews:'Știri de ultimă oră', alNewsNote:'Apare o știre despre un simbol urmărit',
    alInsider:'Tranzacții insider', alInsiderNote:'Cumpărări și vânzări Form 4 ale conducerii',
    alFilings:'Raportări la reglementator', alFilingsNote:'8-K, 10-Q, 13D și alte raportări materiale',
    alRating:'Schimbări de rating', alRatingNote:'Îmbunătățiri, retrogradări și ținte revizuite',
    alEarnings:'Raportări financiare', alEarningsNote:'În momentul publicării rezultatelor',
    alMove:'Variație de preț', alMoveNote:'Variație zilnică peste pragul tău',
    calendarTitle:'Calendar', calendarEmpty:'Niciun eveniment programat',
    evEarnings:'Raportare', evExDiv:'Ex-dividend', evPay:'Dividend plătit', evGuide:'Prognoză', evDay:'Eveniment investitori', evLockup:'Expirare lock-up',
    whyTitle:'De ce s-a mișcat', whyConfidence:'încredere', whyNone:'Nimic nu explică mișcarea',
    conflictTitle:'Unde se contrazic datele', conflictNone:'Analiștii, insiderii și prețul indică la fel',
    posTitle:'Poziția ta', posEmpty:'Fără poziție', posAdd:'Adaugă poziție', posEdit:'Editează', posShares:'Acțiuni', posCost:'Preț de achiziție',
    posValue:'Valoare', posDay:'Azi', posTotal:'De la achiziție', posSave:'Salvează', posRemove:'Șterge', posWeight:'din portofoliu',
    crowdTitle:'Aglomerare', crowdOf:'dintre utilizatori dețin', crowdContrarian:'Aproape nedeținut — ești devreme sau singur',
    crowdCrowded:'Foarte aglomerat — ieșirile se îngustează când sentimentul se schimbă', crowdNormal:'Deținere normală',
    crowdBook:'Aglomerarea portofoliului', crowdBookNote:'Ponderat după mărimea poziției',
    zoneEdge:'Rar deținut', zoneNormal:'Normal', zoneCrowded:'Aglomerat', zoneAlarm:'Foarte aglomerat',
    ledger:'Registru', ledgerTitle:'Registrul regretelor', ledgerNote:'Fiecare știre ignorată și ce a făcut prețul după.',
    ledgerEmpty:'Nimic ignorat încă. Sari peste o știre în flux și apare aici.',
    ledgerMissed:'Ratat', ledgerDodged:'Evitat', ledgerFlat:'Fără mișcare', ledgerPendingRow:'Se urmărește', ledgerSince:'de când ai ignorat',
    ledgerScore:'Acuratețea ignorării', ledgerScoreNote:'Doar deciziile evaluate', ledgerClear:'Golește registrul',
    ledgerPending:'În așteptare', ledgerPendingNote:'Prea devreme de evaluat', ledgerAll:'Toate', ledgerUndo:'Anulează', ledgerEmptyFilter:'Nimic în această categorie încă.',
    dismiss:'Ignoră', dismissed:'Ignorat — îl urmărim',
    auditTitle:'Activitate de securitate', auditNote:'Doar adăugări. Păstrat pe acest cont, cele noi primele.',
    auditEmpty:'Nimic înregistrat încă.',
    evSignin:'Autentificare', evSignout:'Deconectare', evSignoutAll:'Deconectare de pe toate dispozitivele',
    evTwofaOn:'Verificare în doi pași activată', evTwofaOff:'Verificare în doi pași dezactivată',
    evDeviceRevoked:'Dispozitiv revocat', evLocked:'Blocat la inactivitate', evUnlockFailed:'Deblocare eșuată',
    evPasswordChanged:'Parolă schimbată',
    stack:'Stivă', stackTitle:'Stivă de comparație', stackShow:'Stivă', stackHide:'Ascunde',
    stackEmpty:'Fixează simboluri — apasă P pe un rând din flux sau ⌘K apoi +NVDA — ca să le citești pe aceeași scală.',
    stackPin:'Fixează', stackUnpin:'Elimină', stackClear:'Golește stiva', stackNorm:'Indexat la 100 · o lună',
    stackSpread:'Ecart', stackCrowdCol:'Aglomerare', stackAccCol:'Ignorate', stackLead:'Lider', stackLag:'Codaș',
    cmdPlaceholder:'NVDA · +NVDA pentru fixare · vol>2 · registru',
    cmdOpenHint:'Deschide', cmdPinHint:'Fixează în stivă', cmdScreenHint:'Filtru', cmdGoHint:'Mergi la', cmdNone:'Nicio potrivire',
    cmdKeys:'⌘K comandă · J / K navigare · P fixare · X ignoră · Enter deschide',
    signalsTitle:'Insider și raportări', signalsEmpty:'Nicio raportare în ultimele 30 de zile',
    sigBuy:'a cumpărat', sigSell:'a vândut', sigFiling:'Raportare', sigShares:'acț.',
    notifTickers:'Simboluri urmărite', notifTickersNote:'Notificare la potrivire', notifMove:'Prag de variație', notifMoveNote:'Variație zilnică absolută', notifQuiet:'Ore silențioase', notifQuietNote:'Blocate peste noapte',
    tabFeed:'Flux', tabList:'Listă', tabAdd:'Adaugă', tabMore:'Mai mult', tabYou:'Tu', langNote:'Știrile, notele și alertele sunt livrate în română.' },
  DE: { terminal:'Terminal-Build · v2', mobile:'Mobil', desktop:'Desktop', free:'Gratis', pro:'Pro', viewPro:'Als Pro ansehen', viewFree:'Als Gratis ansehen',
    interval:'Scan-Intervall', sources:'Quellen', pitch:'Jeder verfolgte Ticker wird im festgelegten Intervall gescannt. Push kommt, sobald eine Meldung erscheint — nicht erst beim nächsten Aktualisieren.',
    contGoogle:'Weiter mit Google', contApple:'Weiter mit Apple', contEmail:'Weiter mit E-Mail',
    feed:'Feed', following:'Verfolgt', market:'Markt', score:'Score', volAvg:'Vol vs Ø', source:'Quelle', watch:'Beachten',
    delayed24:'24 Std. verzögert', proYesterday:'Pro hat das gestern gelesen', removeDelay:'Verzögerung entfernen', delayLabel:'Verzögerung 24 Std.', lastScan:'letzter Scan 09:41',
    watchlist:'Watchlist', ticker:'Ticker', last:'Letzter', chg:'Änd', pushOff:'kein Push', pushOn:'Push 30m', addTicker:'Ticker hinzufügen',
    capNote:'Gratis begrenzt die Liste auf drei und sendet keine Pushes. Pro ist unbegrenzt, im 30-Minuten-Intervall.', liftCap:'Limit aufheben',
    stories24:'Meldungen 24 Std.', storiesWord:'Meldungen', add:'Hinzu', added:'Hinzugefügt', remove:'Entfernen', match:'Treffer', topVolume:'Höchstes Meldungsvolumen · 24 Std.',
    backFeed:'← Feed', back:'← Zurück', newsScore:'News-Score', storiesN:'28 Meldungen', analyst:'Analysten', earnings:'Zahlen', theCall:'Die Einschätzung', tape:'Tape',
    freqFree:'Gratis: 24 Std. Verzögerung, kein Push, ein Scan pro Tag.', freqPro:'Push wird gesendet, sobald ein Scan etwas findet.',
    addToList:'%s zur Watchlist', enablePush:'Push aktivieren · Upgrade', pushEnabled:'Push aktiv · %s',
    paywallTitle:'Ein ganzer Tag Vorsprung', paywallSub:'Gratis liest die Nachrichten 24 Stunden später. Pro liest sie sofort.',
    perMonth:'/ Mon. · 60 $ / Jahr', start7:'7 Tage gratis starten', stayFree:'Bei Gratis bleiben',
    rowLatency:'Feed-Verzögerung', rowTickers:'Verfolgte Ticker', rowPush:'Push-Benachrichtigungen', rowAnalyst:'Analysten-Details', rowChart:'Chart-Historie', rowDigest:'Digest vor Handelsstart', unlimited:'Unbegrenzt', full:'Voll', max:'Max',
    more:'Mehr', portfolio:'Portfolio', portfolioNote:'Einstandskurs, Gewichtung, G/V im Verhältnis zu den News', calendar:'Zahlenkalender', calendarNote:'Termine und Überraschungshistorie pro Ticker',
    screener:'Screener', screenerNote:'Nach Meldungsvolumen filtern', noMatch:'Kein Ticker gefunden', noMatchNote:'Für die Suche im gesamten Markt über das Demo-Universum hinaus einen Finnhub-Token verbinden.', liveReq:'Live', noData:'Keine Daten', needsLive:'Live-Daten erforderlich', needsLiveNote:'Dieser Ticker liegt außerhalb des Demo-Datensatzes. Für Kurs, Chart und Meldungen einen Finnhub-Token in Tweaks verbinden.', filterAll:'Alle', filterVol:'Vol ≥ 2×', filterEarn:'Zahlen ≤ 14 T', filterStories:'Meiste Meldungen', digests:'Digests', digestsNote:'E-Mail um 06:30 vor Handelsstart', broker:'Broker-Anbindung', brokerNote:'Positionen automatisch importieren',
    account:'Konto', plan:'Tarif', tickers:'Ticker', appLang:'App-Sprache', contentLang:'Inhaltssprache',
    appLangNote:'Buttons, Bezeichnungen und Menüs erscheinen auf Deutsch.', quiet:'Ruhezeiten · 22:00–07:00', manageSub:'Abo verwalten', signOut:'Abmelden',
    upgradeBtn:'Upgrade · 7 $/Mon.', managePro:'Pro verwalten', goPro:'Pro holen', removed:'Entfernt', noNews:'Keine Meldungen in den letzten 24 Std.',
    alertTypes:'Alarmtypen', alertTypesNote:'Was einen Push auslöst. Außer News alles standardmäßig aus.',
    alNews:'Eilmeldungen', alNewsNote:'Eine Meldung zu einem verfolgten Ticker erscheint',
    alInsider:'Insidergeschäfte', alInsiderNote:'Form-4-Käufe und -Verkäufe von Organmitgliedern',
    alFilings:'Pflichtmitteilungen', alFilingsNote:'8-K, 10-Q, 13D und weitere wesentliche Meldungen',
    alRating:'Rating-Änderungen', alRatingNote:'Hoch- und Abstufungen, geänderte Kursziele',
    alEarnings:'Quartalszahlen', alEarningsNote:'Sobald die Ergebnisse veröffentlicht sind',
    alMove:'Kursbewegung', alMoveNote:'Tagesveränderung über Ihrer Schwelle',
    calendarTitle:'Kalender', calendarEmpty:'Keine geplanten Termine',
    evEarnings:'Zahlen', evExDiv:'Ex-Dividende', evPay:'Dividende gezahlt', evGuide:'Prognose', evDay:'Investorentermin', evLockup:'Lock-up-Ablauf',
    whyTitle:'Warum es sich bewegt hat', whyConfidence:'Konfidenz', whyNone:'Nichts erklärt es',
    conflictTitle:'Wo sich die Belege widersprechen', conflictNone:'Analysten, Insider und Kurs zeigen in dieselbe Richtung',
    posTitle:'Ihre Position', posEmpty:'Keine Position', posAdd:'Position hinzufügen', posEdit:'Bearbeiten', posShares:'Stück', posCost:'Einstandskurs',
    posValue:'Wert', posDay:'Heute', posTotal:'Seit Kauf', posSave:'Speichern', posRemove:'Entfernen', posWeight:'des Portfolios',
    crowdTitle:'Positionierung', crowdOf:'der Nutzer halten dies', crowdContrarian:'Kaum gehalten — Sie sind früh oder allein',
    crowdCrowded:'Stark überlaufen — die Ausgänge werden eng, wenn die Stimmung dreht', crowdNormal:'Normale Verbreitung',
    crowdBook:'Portfolio-Positionierung', crowdBookNote:'Gewichtet nach Positionsgröße',
    zoneEdge:'Kaum gehalten', zoneNormal:'Normal', zoneCrowded:'Überlaufen', zoneAlarm:'Stark überlaufen',
    ledger:'Journal', ledgerTitle:'Reue-Journal', ledgerNote:'Jede übersprungene Meldung und was der Kurs danach tat.',
    ledgerEmpty:'Noch nichts übersprungen. Überspringen Sie eine Meldung im Feed — sie landet hier.',
    ledgerMissed:'Verpasst', ledgerDodged:'Vermieden', ledgerFlat:'Keine Bewegung', ledgerPendingRow:'Wird verfolgt', ledgerSince:'seit dem Überspringen',
    ledgerScore:'Treffsicherheit', ledgerScoreNote:'Nur bewertete Entscheidungen', ledgerClear:'Journal leeren',
    ledgerPending:'Offen', ledgerPendingNote:'Noch nicht bewertbar', ledgerAll:'Alle', ledgerUndo:'Rückgängig', ledgerEmptyFilter:'Hier ist noch nichts.',
    dismiss:'Überspringen', dismissed:'Übersprungen — wird verfolgt',
    auditTitle:'Sicherheitsaktivität', auditNote:'Nur Anhängen. Auf diesem Konto gespeichert, neueste zuerst.',
    auditEmpty:'Noch nichts erfasst.',
    evSignin:'Angemeldet', evSignout:'Abgemeldet', evSignoutAll:'Überall abgemeldet',
    evTwofaOn:'Zwei-Faktor aktiviert', evTwofaOff:'Zwei-Faktor deaktiviert',
    evDeviceRevoked:'Gerät entfernt', evLocked:'Bei Inaktivität gesperrt', evUnlockFailed:'Entsperren fehlgeschlagen',
    evPasswordChanged:'Passwort geändert',
    stack:'Stapel', stackTitle:'Vergleichsstapel', stackShow:'Stapel', stackHide:'Ausblenden',
    stackEmpty:'Titel anheften — P auf einer Feed-Zeile oder ⌘K und +NVDA — um sie auf einer Skala zu lesen.',
    stackPin:'Anheften', stackUnpin:'Lösen', stackClear:'Stapel leeren', stackNorm:'Indexiert auf 100 · 1 Monat',
    stackSpread:'Spanne', stackCrowdCol:'Positionierung', stackAccCol:'Übersprungen', stackLead:'Spitze', stackLag:'Schlusslicht',
    cmdPlaceholder:'NVDA · +NVDA zum Anheften · vol>2 · Journal',
    cmdOpenHint:'Öffnen', cmdPinHint:'An Stapel anheften', cmdScreenHint:'Filter', cmdGoHint:'Gehe zu', cmdNone:'Kein Treffer',
    cmdKeys:'⌘K Befehl · J / K bewegen · P anheften · X überspringen · Enter öffnen',
    signalsTitle:'Insider & Meldungen', signalsEmpty:'Keine Meldungen in den letzten 30 Tagen',
    sigBuy:'kaufte', sigSell:'verkaufte', sigFiling:'Meldung', sigShares:'Stk.',
    notifTickers:'Verfolgte Ticker', notifTickersNote:'Push bei Scan-Treffer', notifMove:'Bewegungsschwelle', notifMoveNote:'Absolute Tagesveränderung', notifQuiet:'Ruhezeiten', notifQuietNote:'Nachts unterdrückt',
    tabFeed:'Feed', tabList:'Liste', tabAdd:'Neu', tabMore:'Mehr', tabYou:'Du', langNote:'Meldungen, Hinweise und Alerts werden auf Deutsch geliefert.' }
};
const AUTH = {
  EN: {
    authKicker:'Sign in — or create an account on the spot.', contICloud:'Continue with iCloud', orEmail:'or continue with email',
    emailLabel:'Email', pwLabel:'Password', pwShow:'Show', pwHide:'Hide',
    pwScores:['—','Very weak','Weak','Fair','Strong'], pwBreach:'Seen in known breaches — choose another.',
    pwAdd:'Add', hintLen:'8+ characters', hintCase:'upper and lower case', hintDigit:'a number', hintSymbol:'a symbol',
    contBtn:'Continue', authFoot:'First sign-in creates the account. No card until you go Pro.',
    authErrEmail:'Enter a valid email address', authErrPw:'Password must be at least 8 characters',
    obTitle:'Follow three to start', obSub:'Free tracks three tickers. Pick the ones you actually watch — swap them any time.',
    obCount:'selected', obGo:'Open the feed', obSkip:'Start with the defaults',
    security:'Security', securityNote:'Sessions, two-factor and connected accounts', manageSecurity:'Security & sessions',
    sessionsTitle:'Active sessions', thisDevice:'This device', revoke:'Revoke', signOutAll:'Sign out everywhere',
    twofaTitle:'Two-factor authentication', twofaNote:'A code from your authenticator app on every new sign-in.',
    twofaSetup:'Set up authenticator', twofaKey:'Setup key', twofaKeyNote:'Enter this key in your authenticator app, then confirm the code it shows.',
    twofaCode:'6-digit code', twofaVerify:'Verify and enable', twofaDisable:'Turn off', twofaCancel:'Cancel',
    twofaBadCode:'Enter the six digits your app is showing now',
    recoveryTitle:'Recovery codes', recoveryNote:'Each code works once. Keep them somewhere offline.', recoveryCopy:'Copy codes',
    alertsTitle:'Login alerts', alertsNote:'Email me when a new device signs in',
    connectedTitle:'Connected accounts', link:'Link', unlink:'Unlink', linked:'Linked', primaryAcct:'Primary',
    timeoutTitle:'Inactivity timeout', timeoutNote:'Lock the app after a period without activity.', timeoutNever:'Never', timeoutDemo:'90 s',
    lockedTitle:'Locked', lockedNote:'Locked after inactivity. Enter your password to continue.', unlockBtn:'Unlock', notYou:'Not you? Sign out',
    on:'On', off:'Off',
    toastSignedIn:'Signed in', toastSignedOutAll:'Signed out on every device', toastTwofaOn:'Two-factor enabled',
    toastTwofaOff:'Two-factor turned off', toastRevoked:'Session revoked', toastLinked:'linked', toastUnlinked:'unlinked',
    toastLocked:'Locked · inactivity', toastCopied:'Recovery codes copied',
    appearance:'Appearance', themeSystem:'System', themeLight:'Light', themeDark:'Dark',
    themeNoteSystem:'Follows your operating system setting.', themeNoteLight:'Light surfaces, ink on paper.', themeNoteDark:'Dark terminal surfaces.'
  },
  RO: {
    authKicker:'Autentifică-te — sau creează un cont pe loc.', contICloud:'Continuă cu iCloud', orEmail:'sau continuă cu e-mail',
    emailLabel:'E-mail', pwLabel:'Parolă', pwShow:'Arată', pwHide:'Ascunde',
    pwScores:['—','Foarte slabă','Slabă','Acceptabilă','Puternică'], pwBreach:'Apare în scurgeri de date cunoscute — alege alta.',
    pwAdd:'Adaugă', hintLen:'minim 8 caractere', hintCase:'majuscule și minuscule', hintDigit:'o cifră', hintSymbol:'un simbol',
    contBtn:'Continuă', authFoot:'Prima autentificare creează contul. Card doar când treci pe Pro.',
    authErrEmail:'Introdu o adresă de e-mail validă', authErrPw:'Parola trebuie să aibă cel puțin 8 caractere',
    obTitle:'Începe cu trei simboluri', obSub:'Varianta gratuită urmărește trei simboluri. Alege-le pe cele care contează — le schimbi oricând.',
    obCount:'selectate', obGo:'Deschide fluxul', obSkip:'Începe cu cele implicite',
    security:'Securitate', securityNote:'Sesiuni, autentificare în doi pași și conturi conectate', manageSecurity:'Securitate și sesiuni',
    sessionsTitle:'Sesiuni active', thisDevice:'Acest dispozitiv', revoke:'Revocă', signOutAll:'Deconectează tot',
    twofaTitle:'Autentificare în doi pași', twofaNote:'Un cod din aplicația de autentificare la fiecare conectare nouă.',
    twofaSetup:'Configurează aplicația', twofaKey:'Cheie de configurare', twofaKeyNote:'Introdu cheia în aplicația de autentificare, apoi confirmă codul afișat.',
    twofaCode:'Cod din 6 cifre', twofaVerify:'Verifică și activează', twofaDisable:'Dezactivează', twofaCancel:'Renunță',
    twofaBadCode:'Introdu cele șase cifre afișate acum de aplicație',
    recoveryTitle:'Coduri de recuperare', recoveryNote:'Fiecare cod funcționează o singură dată. Păstrează-le offline.', recoveryCopy:'Copiază codurile',
    alertsTitle:'Alerte de conectare', alertsNote:'Trimite e-mail când un dispozitiv nou se conectează',
    connectedTitle:'Conturi conectate', link:'Conectează', unlink:'Deconectează', linked:'Conectat', primaryAcct:'Principal',
    timeoutTitle:'Blocare la inactivitate', timeoutNote:'Blochează aplicația după o perioadă fără activitate.', timeoutNever:'Niciodată', timeoutDemo:'90 s',
    lockedTitle:'Blocat', lockedNote:'Blocat după inactivitate. Introdu parola pentru a continua.', unlockBtn:'Deblochează', notYou:'Nu ești tu? Deconectare',
    on:'Activ', off:'Inactiv',
    toastSignedIn:'Autentificat', toastSignedOutAll:'Deconectat de pe toate dispozitivele', toastTwofaOn:'Doi pași activat',
    toastTwofaOff:'Doi pași dezactivat', toastRevoked:'Sesiune revocată', toastLinked:'conectat', toastUnlinked:'deconectat',
    toastLocked:'Blocat · inactivitate', toastCopied:'Coduri copiate',
    appearance:'Aspect', themeSystem:'Sistem', themeLight:'Deschis', themeDark:'Închis',
    themeNoteSystem:'Urmează setarea sistemului de operare.', themeNoteLight:'Suprafețe deschise, cerneală pe hârtie.', themeNoteDark:'Suprafețe închise, stil terminal.'
  },
  DE: {
    authKicker:'Anmelden — oder direkt ein Konto anlegen.', contICloud:'Weiter mit iCloud', orEmail:'oder weiter mit E-Mail',
    emailLabel:'E-Mail', pwLabel:'Passwort', pwShow:'Zeigen', pwHide:'Verbergen',
    pwScores:['—','Sehr schwach','Schwach','Mittel','Stark'], pwBreach:'In bekannten Leaks gefunden — bitte anderes wählen.',
    pwAdd:'Ergänzen', hintLen:'8+ Zeichen', hintCase:'Gross- und Kleinschreibung', hintDigit:'eine Zahl', hintSymbol:'ein Sonderzeichen',
    contBtn:'Weiter', authFoot:'Die erste Anmeldung erstellt das Konto. Karte erst bei Pro.',
    authErrEmail:'Gültige E-Mail-Adresse eingeben', authErrPw:'Passwort braucht mindestens 8 Zeichen',
    obTitle:'Mit drei Tickern starten', obSub:'Gratis verfolgt drei Ticker. Wähle die, die du wirklich beobachtest — jederzeit änderbar.',
    obCount:'ausgewählt', obGo:'Feed öffnen', obSkip:'Mit Standardwerten starten',
    security:'Sicherheit', securityNote:'Sitzungen, Zwei-Faktor und verbundene Konten', manageSecurity:'Sicherheit und Sitzungen',
    sessionsTitle:'Aktive Sitzungen', thisDevice:'Dieses Gerät', revoke:'Widerrufen', signOutAll:'Überall abmelden',
    twofaTitle:'Zwei-Faktor-Authentifizierung', twofaNote:'Ein Code aus der Authenticator-App bei jeder neuen Anmeldung.',
    twofaSetup:'Authenticator einrichten', twofaKey:'Einrichtungsschlüssel', twofaKeyNote:'Schlüssel in der Authenticator-App eintragen, dann den angezeigten Code bestätigen.',
    twofaCode:'6-stelliger Code', twofaVerify:'Prüfen und aktivieren', twofaDisable:'Deaktivieren', twofaCancel:'Abbrechen',
    twofaBadCode:'Die sechs Ziffern eingeben, die die App jetzt zeigt',
    recoveryTitle:'Wiederherstellungscodes', recoveryNote:'Jeder Code gilt einmal. Offline aufbewahren.', recoveryCopy:'Codes kopieren',
    alertsTitle:'Anmelde-Warnungen', alertsNote:'E-Mail, wenn sich ein neues Gerät anmeldet',
    connectedTitle:'Verbundene Konten', link:'Verbinden', unlink:'Trennen', linked:'Verbunden', primaryAcct:'Primär',
    timeoutTitle:'Sperre bei Inaktivität', timeoutNote:'App nach einer Zeit ohne Aktivität sperren.', timeoutNever:'Nie', timeoutDemo:'90 s',
    lockedTitle:'Gesperrt', lockedNote:'Nach Inaktivität gesperrt. Passwort eingeben, um fortzufahren.', unlockBtn:'Entsperren', notYou:'Nicht du? Abmelden',
    on:'Ein', off:'Aus',
    toastSignedIn:'Angemeldet', toastSignedOutAll:'Überall abgemeldet', toastTwofaOn:'Zwei-Faktor aktiv',
    toastTwofaOff:'Zwei-Faktor aus', toastRevoked:'Sitzung widerrufen', toastLinked:'verbunden', toastUnlinked:'getrennt',
    toastLocked:'Gesperrt · Inaktivität', toastCopied:'Codes kopiert',
    appearance:'Erscheinungsbild', themeSystem:'System', themeLight:'Hell', themeDark:'Dunkel',
    themeNoteSystem:'Folgt der Einstellung des Betriebssystems.', themeNoteLight:'Helle Flächen, Tinte auf Papier.', themeNoteDark:'Dunkle Terminal-Flächen.'
  }
};
Object.keys(AUTH).forEach(k => Object.assign(UI[k], AUTH[k]));
// Sector grouping. Used to tell a company-specific move apart from a sector-wide one.
const SECTORS = {
  Semiconductors:['NVDA','AMD','AVGO','INTC','TSM','ASML','MU','QCOM','ARM','TXN','IFX','STM'],
  'Big tech':['AAPL','MSFT','GOOGL','AMZN','META','NFLX','ORCL','CRM','ADBE','SAP','IBM','BABA'],
  Autos:['TSLA','F','GM','BMW','MBG','VOW3','RIVN','LCID','STLA'],
  Banks:['JPM','BAC','GS','MS','C','WFC','DB','HSBC','UBS','BNP'],
  Pharma:['LLY','PFE','MRK','JNJ','ABBV','NOVO','AZN','GSK','SAN','BAYN'],
  Energy:['XOM','CVX','SHEL','BP','TTE','COP','ENI'],
  Industrials:['SIE','RHM','BA','CAT','GE','HON','AIR','MMM']
};
const SECTOR_OF = {};
Object.keys(SECTORS).forEach(s => SECTORS[s].forEach(t => { SECTOR_OF[t] = s; }));
// Share of StockNews users holding each name (demo figure; the server aggregates real
// positions anonymously). Crowding is a risk signal retail products never surface.
const CROWD = {
  NVDA:84, AAPL:79, TSLA:71, MSFT:64, AMZN:58, GOOGL:52, META:44, AMD:41, AVGO:29, PLTR:38,
  ASML:22, NOVO:17, SAP:12, SIE:9, RHM:14, BMW:8, SHEL:7, BABA:19, INTC:26, MU:18,
  JPM:15, GS:9, LLY:21, PFE:11, XOM:10, TSM:24, ARM:16, NFLX:31, ORCL:20, CRM:13
};
window.HIF = { NEWS, FOLLOWS, UNIVERSE, EVENTS, SIGNALS, SECTORS, SECTOR_OF, CROWD, UI };
})();
